version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: one-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped